export const PROJECTS = [
  {
    id: 'tnp-oms',
    number: '01',
    eyebrow: 'Capstone Project',
    title: 'TNP Orphanage Management System',
    shortTitle: 'TNP-OMS',
    description: 'A full-stack capstone and research project created to support orphanage management workflows.',
    role: 'Research Lead & Full Stack Developer',
    impact: null,
    technologies: ['HTML', 'CSS', 'TailwindCSS', 'JavaScript', 'PHP', 'Firebase'],
    liveUrl: 'https://tahananngpagmamahal.capstone-two.com/login',
    screenshot: '/projects/CapstoneOMS.png',
    screenshotAvailable: true,
    accent: '#00e5ff',
    secondaryAccent: '#6557ff'
  },
  {
    id: 'warehouse-internship',
    number: '02',
    eyebrow: 'Internship Project',
    title: 'Warehouse Management System',
    shortTitle: 'Warehouse',
    description: 'A configurable project entry reserved for the supplied warehouse internship application preview.',
    role: 'Full Stack Web Developer Intern',
    impact: null,
    technologies: ['HTML', 'TailwindCSS', 'TypeScript', 'Vue.js', 'Laravel', 'Inertia.js', 'MySQL'],
    liveUrl: 'https://jounteux-warehouse-management-production.up.railway.app/login',
    screenshot: '/projects/WarehouseInternship.png',
    screenshotAvailable: true,
    accent: '#22d3ee',
    secondaryAccent: '#8b5cf6'
  },
  {
    id: 'coffee-shop',
    number: '03',
    eyebrow: 'Featured Project',
    title: 'E-Commerce Coffee Shop Project',
    shortTitle: 'Coffee Shop',
    description: 'A configurable project entry for a comprehensive e-commerce coffee shop platform with customer and administrator interfaces, featuring an integrated Point of Sale (POS) system for managing in-store sales, online orders, inventory, products, customers, and business analytics.',
    role: 'Full Stack Web Developer',
    impact: null,
    technologies: ['HTML', 'CSS', 'PHP', 'MySQL', 'Xampp'],
    liveUrl: null,
    screenshot: '/projects/CoffeeShop.png',
    screenshotAvailable: true,
    accent: '#38bdf8',
    secondaryAccent: '#a855f7'
  },
  {
    id: 'silver-thatch',
    number: '04',
    eyebrow: 'Featured Project',
    title: 'Silver Thatch',
    shortTitle: 'Silver Thatch',
    description: 'A personal frontend redesign project that reimagines the Silver Thatch website with a modern, responsive interface. This project focuses solely on the frontend, with no backend functionality.',
    role: 'Frontend Web Developer',
    impact: null,
    technologies: ['HTML', 'TailwindCSS', 'JavaScript', 'React.js'],
    liveUrl: 'https://silver-thatch-pensions-redesign-iux.vercel.app/',
    screenshot: '/projects/SilverThatch.png',
    screenshotAvailable: true,
    accent: '#67e8f9',
    secondaryAccent: '#7c3aed'
  }
]
